version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=challenge_db 
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./script_db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports: 
      - '8081:8081'
volumes:
  db:
    driver: local